#!/usr/bin/env python3
"""Build the educational landing page from the current material catalog."""
from __future__ import annotations

import argparse
from html import escape
from pathlib import Path
from repo_catalog import discover, children, top_level_dirs, top_level_files, md_escape, relative_repo_link

SUBJECTS = {
    'МПС': ('Микропроцессорные системы', 'Архитектура микропроцессоров, представление данных, адресация, ассемблер, шины и проектирование микропроцессорных устройств.'),
    'ПМК': ('Программирование микроконтроллеров', 'Архитектура и программирование микроконтроллеров, Arduino, ARM Cortex-M, периферия, подключение устройств и отладка управляющих программ.'),
}
DOCUMENTS = {
    'РПД': ('Рабочие программы', 'Содержание дисциплин, тематическое планирование и требования к результатам обучения.'),
    'ФОС': ('Контроль знаний', 'Материалы для проверки знаний и входного контроля.'),
    'АккМон': ('Аккредитация и оценочные материалы', 'Вопросы к аккредитации и фонды оценочных средств по МПС и ПМК.'),
}

def link(title, rel):
    return f'[{md_escape(title)}]({relative_repo_link(rel)})'

def material_label(item):
    # Generic headings in accreditation files otherwise produce identical labels.
    title = item.title
    if title.casefold() == 'вопросы к аккредитации':
        title += ' — ' + ('МПС' if 'Микропроцессорные' in item.rel else 'ПМК')
    return title

def listing(items, parent):
    """Flatten folders into compact material lists without a directory tree."""
    lines = []
    for item in children(items, parent):
        if item.kind == 'dir':
            lines.extend(listing(items, item.rel))
        else:
            lines.append('- ' + link(material_label(item), item.rel))
    return lines

def details(title, lines):
    return ['<details>', f'<summary><strong>{escape(title)}</strong></summary>', '', *lines, '', '</details>', '']

def build(repo: Path) -> str:
    items = discover(repo)
    roots = {Path(x.rel).name: x for x in top_level_dirs(items)}
    lines = [
        '<!-- Generated by .github/scripts/build_readme.py. Edit the generator to change the layout. -->',
        '# 🎓 Таврический колледж', '',
        '**Учебно-методические материалы по микропроцессорным системам и программированию микроконтроллеров**', '',
        'Специальность **09.02.01 «Компьютерные системы и комплексы»** · **3 и 4 курс**', '',
        'Лекции, практические задания, примеры выполнения и материалы для контроля знаний. '
        'Репозиторий помогает изучать устройство микропроцессорных систем, разрабатывать программы для микроконтроллеров и готовиться к аттестации.', '',
        '[Учебные материалы](#учебные-материалы) · [Документы и аттестация](#документы-и-аттестация) · [Как пользоваться](#как-пользоваться)', '',
        '---', '', '<a id="учебные-материалы"></a>', '## 📚 Учебные материалы', '',
        'Выберите дисциплину и курс. Ссылки в таблице ведут к папкам с материалами; ниже можно раскрыть список и открыть конкретную лекцию или работу.', '',
        '| Дисциплина | Курс | Лекции | Практические работы |',
        '| :--- | :---: | :---: | :---: |',
    ]
    for key, (title, _) in SUBJECTS.items():
        if key not in roots: continue
        for course in children(items, roots[key].rel):
            if course.kind != 'dir': continue
            sections = {Path(x.rel).name: x for x in children(items, course.rel) if x.kind == 'dir'}
            cells = [link('Открыть', sections[name].rel) if name in sections else '—'
                     for name in ('Лекции', 'Практические задания')]
            lines.append(f'| {title} | {md_escape(Path(course.rel).name)} | {cells[0]} | {cells[1]} |')
    lines.append('')
    for key, (title, description) in SUBJECTS.items():
        if key not in roots: continue
        lines += [f'### {title}', '', description, '']
        for course in children(items, roots[key].rel):
            if course.kind != 'dir': continue
            content = []
            for section in children(items, course.rel):
                if section.kind == 'dir':
                    content += [f'**{md_escape(Path(section.rel).name)}**', '', *listing(items, section.rel), '']
                else:
                    content += ['- ' + link(material_label(section), section.rel)]
            lines += details(Path(course.rel).name + ' — список материалов', content or ['_Материалы пока не опубликованы._'])
    lines += ['---', '', '<a id="документы-и-аттестация"></a>', '## 📋 Документы и аттестация', '',
              '| Раздел | Что внутри |', '| :--- | :--- |']
    other_roots = [x for name, x in roots.items() if name not in SUBJECTS]
    for root in other_roots:
        name = Path(root.rel).name
        title, description = DOCUMENTS.get(name, ('Демонстрационный экзамен', 'Образец задания, КИМ и приложения.') if name.startswith('Демоэкзамен') else (root.title, 'Дополнительные материалы репозитория.'))
        lines.append(f'| {link(title, root.rel)} | {description} |')
    lines.append('')
    for root in other_roots:
        name = Path(root.rel).name
        title = DOCUMENTS.get(name, (root.title, ''))[0]
        lines += details(title + ' — список документов', listing(items, root.rel) or ['_Документы пока не опубликованы._'])
    files = top_level_files(items)
    if files:
        lines += details('Дополнительные файлы', ['- ' + link(material_label(x), x.rel) for x in files])
    lines += [
        '---', '', '<a id="как-пользоваться"></a>', '## 🧭 Как пользоваться', '',
        '1. Выберите свою дисциплину и курс в таблице выше.',
        '2. Откройте нужную лекцию или практическую работу.',
        '3. Перед выполнением работы прочитайте требования к оборудованию, заданию и отчёту. Если предусмотрены варианты, используйте правило выбора, указанное в самой работе.',
        '4. Для подготовки к контролю знаний и аттестации перейдите в раздел «Документы и аттестация».', '',
        'Материалы в формате **Markdown (.md)** можно читать прямо на GitHub вместе с иллюстрациями и примерами кода. **PDF** можно открыть для просмотра или скачать.', '',
        '<details>', '<summary>Для преподавателя: обновление навигации</summary>', '',
        'Списки материалов формируются автоматически после отправки изменений в ветку `main`. '
        'Генератор сохраняет оформление страницы и обновляет ссылки по фактическому содержимому репозитория. '
        'Новые разделы вне МПС и ПМК появляются в блоке документов.', '',
        'Для изменения описания или оформления отредактируйте `.github/scripts/build_readme.py`. '
        'Ручные изменения в корневом `README.md` будут заменены при следующей сборке.', '',
        '[Дополнительная навигация в Wiki](https://github.com/BysonHunter/Tavrich_college/wiki)', '',
        '</details>', '', '---', '',
        '**Таврический колледж · 09.02.01 «Компьютерные системы и комплексы»**', '',
    ]
    return '\n'.join(lines)

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--repo', default='.')
    parser.add_argument('--output', default='README.md')
    args = parser.parse_args()
    repo = Path(args.repo).resolve()
    output = repo / args.output
    output.write_text(build(repo), encoding='utf-8')
    print(f'README создан: {output}')
    return 0

if __name__ == '__main__':
    raise SystemExit(main())
